/**
 * Centralized Route Constants & Host Configuration for Frontend
 */

export const API_HOST_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_URL || import.meta.env.VITE_API_BASE_URL || '/api',
  AUTH: '/auth',
  USERS: '/users',
  FAMILIES: '/families',
  MEMBERS: '/members',
  NETWORKS: '/networks',
  APPROVALS: '/change-requests',
  AUDIT_LOGS: '/audit-logs',
  BACKUP: '/backup',
};

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  ACTIVATION: '/activate',
  PUBLIC: {
    ROOT: '/public',
    BUSINESS_PLANS: '/public/business-plans',
    FAMILIES: '/public/families',
    FAMILY_PROFILE: '/public/families/:id',
    BUSINESS_REGISTER: '/public/business-register',
    BUSINESS_TRACK: '/public/business-register/track',
  },
  USER: {
    ROOT: '/user',
    DASHBOARD: '/user/dashboard',
    TREE: '/user/tree',
    TREE_VERTICAL: '/user/tree/vertical',
    TREE_HORIZONTAL: '/user/tree/horizontal',
    TREE_FOCUS: '/user/tree/focus',
    NETWORK: '/user/network',
    NETWORK_NOI: '/user/network/noi',
    NETWORK_NGOAI: '/user/network/ngoai',
    NETWORK_DAU_RE: '/user/network/dau-re',
    NETWORK_THONG_GIA: '/user/network/thong-gia',
    MEMBERS: '/user/members',
    MEMBER_PROFILE: '/user/members/profile',
    MY_PROFILE: '/user/profile',
    RELATIONSHIP: '/user/relationship',
    ANNIVERSARIES: '/user/anniversaries',
    EVENTS: '/user/events',
    FUNDS: '/user/funds',
    DOCUMENTS: '/user/documents',
    AI_ASSISTANT: '/user/ai-assistant',
    ANCESTRAL_HALL: '/user/ancestral-hall',
    NOTIFICATIONS: '/user/notifications',
    PRIVACY_SETTINGS: '/user/privacy-settings',
    PRIVACY_PREVIEW: '/user/privacy-preview',
    REPORTS: '/user/reports',
    PROPOSALS: '/user/proposals',
    // Family Management (For owners)
    FAMILY_MANAGEMENT: '/user/family-management',
    FAMILY_RELATIONS: '/user/family-management/relations',
    FAMILY_TREE: '/user/family-management/tree',
    FAMILY_SEARCH: '/user/family-management/search',
    FAMILY_BRANCHES: '/user/family-management/branches',
    FAMILY_APPROVALS: '/user/family-management/approvals',
    FAMILY_ACCOUNTS: '/user/family-management/accounts',
    FAMILY_LINKS: '/user/family-management/links',
    FAMILY_IMPORT_EXPORT: '/user/family-management/import-export',
    FAMILY_LOGS: '/user/family-management/logs',
  },
  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: '/admin/dashboard',
    ACCOUNTS: '/admin/accounts',
    FAMILIES: '/admin/families',
    MEMBERS: '/admin/members',
    FAMILY_LINKS: '/admin/family-links',
    APPROVALS: '/admin/approvals',
    SECURITY_LOGS: '/admin/security-logs',
    BACKUP: '/admin/backup',
  },
};

export default ROUTES;
